#!/bin/bash


./Create_DATA_Aug05ReReco_cfg_Hengne.sh Data_JanA_Aug_RMDUP
./Create_DATA_Aug05ReReco_cfg_Hengne.sh Data_JanA_Aug_MuEG_RMDUP
./Create_DATA_Jul05ReReco_cfg_Hengne.sh Data_JanA_Jul1_RMDUP
./Create_DATA_Jul05ReReco_cfg_Hengne.sh Data_JanA_Jul1_MuEG_RMDUP
./Create_DATA_Jul05ReReco_cfg_Hengne.sh Data_JanA_Jul2_RMDUP
./Create_DATA_Jul05ReReco_cfg_Hengne.sh Data_JanA_Jul2_MuEG_RMDUP
./Create_DATA_Oct03ReReco_cfg_Hengne.sh Data_JanA_Oct_RMDUP
./Create_DATA_Oct03ReReco_cfg_Hengne.sh Data_JanA_Oct_MuEG_RMDUP
./Create_DATA_Promptv1_B_cfg_Hengne.sh Data_JanB_RMDUP
./Create_DATA_Promptv1_B_cfg_Hengne.sh Data_JanB_MuEG_RMDUP
